{
 "title": "Transfer Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Select Instance",
    "query": {
     "query": "up{job=\"prometheus\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Clock", "type": "grafana-clock-panel", "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 } },
  {
   "title": "Transfer Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(case when transfer_status = 'NOT_STARTED' then 1 else 0 end) as NOT_STARTED,\n  sum(case when transfer_status = 'FAILED' then 1 else 0 end) as FAILED,\n  sum(case when transfer_status = 'IN_PROGRESS' then 1 else 0 end) as IN_PROGRESS,\n  sum(case when transfer_status = 'COMPLETED' then 1 else 0 end) as TRANSFERRED\nFROM\n  catalogue_catalogue_item\n"
    }
   ]
  },
  {
   "title": "Sealed State Files Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(case when sealed_state = 'SEALED' then 1 else 0 end) as SEALED,\n  sum(case when sealed_state = 'UNSEALED' then 1 else 0 end) as UNSEALED,\n  sum(case when sealed_state = 'UNSEALING' then 1 else 0 end) as UNSEALING\nFROM\n  catalogue_catalogue_item  WHERE NOT transfer_status='COMPLETED' AND NOT transfer_status='FAILED'\n  "
    }
   ]
  },
  {
   "title": "Transfer Speed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"eth0\"}[$__rate_interval])*8"
    }
   ]
  },
  {
   "title": "Up Time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "5 Min Load",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(\n  sum(\n    rate(node_cpu_seconds_total{mode!=\"idle\"}[5m])\n  ) without (mode)\n) without (cpu)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Cached_bytes - node_memory_Buffers_bytes)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Throughput",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"eth0\"}[$__rate_interval])*8",
     "legendFormat": "Receive"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"eth0\"}[1m]) * 8",
     "legendFormat": "transmit"
    }
   ]
  },
  {
   "title": "Up/Down",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Individual MFT Agent Throughput",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "expr": "(irate(node_network_transmit_bytes_total{instance=\"172.31.12.64:9100\", device=\"eth0\"}[1m]) * 8)"
    },
    {
     "expr": "(irate(node_network_transmit_bytes_total{instance=\"172.31.32.245:9100\",device=\"ens5\"}[1m]) * 8)"
    },
    {
     "expr": "(irate(node_network_transmit_bytes_total{instance=\"172.31.33.81:9100\",device=\"ens5\"}[1m]) * 8)"
    },
    {
     "expr": "(irate(node_network_transmit_bytes_total{instance=\"172.31.41.243:9100\", device=\"ens5\"}[1m]) * 8)"
    }
   ]
  },
  {
   "title": "Total Receive Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device=\"eth0\"}[1m])) * 8 + sum(rate(node_network_receive_bytes_total{device=\"ens5\"}[1m])) * 8",
     "legendFormat": "Total Receive Throughput"
    }
   ]
  }
 ]
}