---
# tasks file for roles/grafana

- name: install gpg
  apt:
    name: gnupg,software-properties-common
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: add gpg hey
  apt_key:
    url: "https://packages.grafana.com/gpg.key"
    validate_certs: no

- name: add repository
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"             
    state: present
    validate_certs: no

- name: install grafana
  apt:
    name: grafana
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: Create HLS Dashboard source directory
  file: path={{hls_dashboard_source_directory}}
    state=directory
    mode=0755
    owner={{ user }}
    group={{ group }}

- name: git checkout from hls_data_transfer_dashboard github repo {{ hls_dashboard_repo }} branch {{ hls_dashboard_git_branch }}
  git: repo="{{ hls_dashboard_repo }}"
    dest="{{ hls_dashboard_source_directory }}/"
    version="{{ hls_dashboard_git_branch }}"
  register: checkout
  failed_when:
    - checkout.failed
    - not 'Local modifications exist in the destination' in checkout.msg
  tags: update

- name: Copy grafana dashboard
  copy: remote_src=True src="{{ hls_dashboard_source_directory }}/grafana/dashboards/" dest="{{grafana_dashobard_location}}"

- name: start service grafana-server
  systemd:
    name: grafana-server
    state: started
    enabled: yes

- name: wait for service up
  uri:
    url: "http://127.0.0.1:3000"
    status_code: 200
  register: __result
  until: __result.status == 200
  retries: 120
  delay: 1

- name: change admin password for grafana gui
  shell : "grafana-cli admin reset-admin-password {{ grafana_admin_password }}"
  register: __command_admin
  changed_when: __command_admin.rc !=0

